### ISSUE TITLE
App is no longer listed in play store

### ISSUE THREAD

**Issue by jasta** [andreitanas/RemoteEV3#1]
I used this app quite a lot with my kids but it doesn't seem to be available anymore?  What are the issues you're facing to get it back online?

**Comment by andreitanas** [comment]
Recently changed legal requirements that Google enforces, such as the need to have a privacy policy even for apps that have no capability to collect data make it not worth maintaining the app in the store.

**Comment by jasta** [comment]
Ok understandable, I'll just build from source
